./lem-in ./valid/big/map_big_1 >> result.txt &&
./lem-in ./valid/big/map_big_10 >> result.txt &&
./lem-in ./valid/big/map_big_11 >> result.txt &&
./lem-in ./valid/big/map_big_12 >> result.txt &&
./lem-in ./valid/big/map_big_13 >> result.txt &&
./lem-in ./valid/big/map_big_14 >> result.txt &&
./lem-in ./valid/big/map_big_15 >> result.txt &&
./lem-in ./valid/big/map_big_16 >> result.txt &&
./lem-in ./valid/big/map_big_17 >> result.txt &&
./lem-in ./valid/big/map_big_18 >> result.txt &&
./lem-in ./valid/big/map_big_19 >> result.txt &&
./lem-in ./valid/big/map_big_2 >> result.txt &&
./lem-in ./valid/big/map_big_20 >> result.txt &&
./lem-in ./valid/big/map_big_21 >> result.txt &&
./lem-in ./valid/big/map_big_22 >> result.txt &&
./lem-in ./valid/big/map_big_223 >> result.txt &&
./lem-in ./valid/big/map_big_23 >> result.txt &&
./lem-in ./valid/big/map_big_24 >> result.txt &&
./lem-in ./valid/big/map_big_25 >> result.txt &&
./lem-in ./valid/big/map_big_26 >> result.txt &&
./lem-in ./valid/big/map_big_27 >> result.txt &&
./lem-in ./valid/big/map_big_28 >> result.txt &&
./lem-in ./valid/big/map_big_29 >> result.txt &&
./lem-in ./valid/big/map_big_3 >> result.txt &&
./lem-in ./valid/big/map_big_30 >> result.txt &&
./lem-in ./valid/big/map_big_31 >> result.txt &&
./lem-in ./valid/big/map_big_32 >> result.txt &&
./lem-in ./valid/big/map_big_33 >> result.txt &&
./lem-in ./valid/big/map_big_34 >> result.txt &&
./lem-in ./valid/big/map_big_35 >> result.txt &&
./lem-in ./valid/big/map_big_36 >> result.txt &&
./lem-in ./valid/big/map_big_365 >> result.txt &&
./lem-in ./valid/big/map_big_37 >> result.txt &&
./lem-in ./valid/big/map_big_38 >> result.txt &&
./lem-in ./valid/big/map_big_39 >> result.txt &&
./lem-in ./valid/big/map_big_4 >> result.txt &&
./lem-in ./valid/big/map_big_40 >> result.txt &&
./lem-in ./valid/big/map_big_41 >> result.txt &&
./lem-in ./valid/big/map_big_42 >> result.txt &&
./lem-in ./valid/big/map_big_43 >> result.txt &&
./lem-in ./valid/big/map_big_44 >> result.txt &&
./lem-in ./valid/big/map_big_45 >> result.txt &&
./lem-in ./valid/big/map_big_458 >> result.txt &&
./lem-in ./valid/big/map_big_46 >> result.txt &&
./lem-in ./valid/big/map_big_47 >> result.txt &&
./lem-in ./valid/big/map_big_48 >> result.txt &&
./lem-in ./valid/big/map_big_49 >> result.txt &&
./lem-in ./valid/big/map_big_5 >> result.txt &&
./lem-in ./valid/big/map_big_50 >> result.txt &&
./lem-in ./valid/big/map_big_51 >> result.txt &&
./lem-in ./valid/big/map_big_52 >> result.txt &&
./lem-in ./valid/big/map_big_6 >> result.txt &&
./lem-in ./valid/big/map_big_7 >> result.txt &&
./lem-in ./valid/big/map_big_8 >> result.txt &&
./lem-in ./valid/big/map_big_9 >> result.txt &&
./lem-in ./valid/big/map_big_98 >> result.txt &&
./lem-in ./valid/map_25 >> result.txt &&
./lem-in ./valid/map_33 >> result.txt &&
./lem-in ./valid/map_39 >> result.txt &&
./lem-in ./valid/map_40 >> result.txt &&
./lem-in ./valid/map_big >> result.txt &&
./lem-in ./valid/map_comments >> result.txt &&
./lem-in ./valid/map_dead_end >> result.txt &&
./lem-in ./valid/map_dead_end_2 >> result.txt &&
./lem-in ./valid/map_dead_end_3 >> result.txt &&
./lem-in ./valid/map_duplicatepipe >> result.txt &&
./lem-in ./valid/map_duplicatepipe1 >> result.txt &&
./lem-in ./valid/map_empty >> result.txt &&
./lem-in ./valid/map_flow_max >> result.txt &&
./lem-in ./valid/map_follow_one_1 >> result.txt &&
./lem-in ./valid/map_hexagonal >> result.txt &&
./lem-in ./valid/map_invalidcommand >> result.txt &&
./lem-in ./valid/map_invalidcommand1 >> result.txt &&
./lem-in ./valid/map_jk_weird >> result.txt &&
./lem-in ./valid/map_loop >> result.txt &&
./lem-in ./valid/map_loop1 >> result.txt &&
./lem-in ./valid/map_overflow >> result.txt &&
./lem-in ./valid/map_pdf >> result.txt &&
./lem-in ./valid/map_shortest >> result.txt &&
./lem-in ./valid/map_simple >> result.txt &&
./lem-in ./valid/map_simple1 >> result.txt &&
./lem-in ./valid/map_simple2 >> result.txt &&
./lem-in ./valid/map_simple_web >> result.txt &&
./lem-in ./valid/map_size_1000 >> result.txt &&
./lem-in ./valid/map_slack >> result.txt &&
./lem-in ./valid/map_slack_2 >> result.txt &&
./lem-in ./valid/map_slack_2_brute >> result.txt &&
./lem-in ./valid/map_subject_1 >> result.txt &&
./lem-in ./valid/map_subject_2 >> result.txt &&
./lem-in ./valid/map_subject_3 >> result.txt &&
./lem-in ./valid/map_subject_3_modified >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_1 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_10 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_11 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_12 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_13 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_14 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_15 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_16 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_17 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_18 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_19 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_2 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_20 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_21 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_22 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_23 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_24 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_25 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_26 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_27 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_28 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_29 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_3 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_30 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_4 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_5 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_6 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_7 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_8 >> result.txt &&
./lem-in ./valid/big_sup/map_big_sup_9 >> result.txt