./lem-in ants_empty
./lem-in ants_nbr_inf_int_min
./lem-in ants_nbr_invalid_char
./lem-in ants_nbr_invalid_char_2
./lem-in ants_nbr_invalid_spacing
./lem-in ants_nbr_neg
./lem-in ants_nbr_too_big
./lem-in empty_line_no_end_defined
./lem-in empty_line_no_tube_to_end
./lem-in empty_map
./lem-in end_before_nb_ants
./lem-in no_end
./lem-in no_start
./lem-in no_tubes
./lem-in room_after_tube
./lem-in room_coord_duplicated
./lem-in room_duplicated
./lem-in room_has_dash
./lem-in room_has_unprintable_char
./lem-in room_invalid_coord
./lem-in room_name_duplicated
./lem-in room_no_y_coord
./lem-in room_start_with_L
./lem-in room_too_much_arg
./lem-in room_without_coord
./lem-in start_and_comments_before_nb_ants
./lem-in start_before_nb_ants
./lem-in start_command_before_tube
./lem-in start_is_end
./lem-in start_not_followed_by_room
./lem-in tube_has_spaces
./lem-in tube_room_does_not_exist
